export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";

export const EMPLOYEE_DETAILS_SUCCESS = "EMPLOYEE_DETAILS_SUCCESS";
export const EMPLOYEE_DETAILS_FAIL = "EMPLOYEE_DETAILS_FAIL";

export const EMPLOYEE_UPDATE_PROFILE_SUCCESS =
  "EMPLOYEE_UPDATE_PROFILE_SUCCESS";
export const EMPLOYEE_UPDATE_PROFILE_FAIL = "EMPLOYEE_UPDATE_PROFILE_FAIL";

export const EMPLOYEE_LIST_SUCCESS = "EMPLOYEE_LIST_SUCCESS";
export const EMPLOYEE_LIST_FAIL = "EMPLOYEE_LIST_FAIL";

export const ATTANDANCE_LIST_SUCCESS = "ATTANDANCE_LIST_SUCCESS";
export const ATTANDANCE_LIST_FAIL = "ATTANDANCE_LIST_FAIL";

export const EMPLOYEE_DELETE_SUCCESS = "EMPLOYEE_DELETE_SUCCESS";
export const EMPLOYEE_DELETE_FAIL = "EMPLOYEE_DELETE_FAIL";

export const EMPLOYEE_ADD_SUCCESS = "EMPLOYEE_DELETE_SUCCESS";
export const EMPLOYEE_ADD_FAIL = "EMPLOYEE_DELETE_FAIL";

// ATTENDANCE

export const CHECK_IN_SUCCESS = "CHECK_IN_SUCCESS";
export const CHECK_IN_FAIL = "CHECK_IN_FAIL";

// AUTH
export const AUTH = "AUTH";
export const AUTH_FAIL = "AUTH_FAIL";

export const LOGOUT = "LOGOUT";
